// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtdhMWWY5YANFCtffF6UWdhCzJ4xADick',
    appId: '1:834219864810:web:0782efa29443f4226b9d93',
    messagingSenderId: '834219864810',
    projectId: 'doan-mobile-2012f',
    authDomain: 'doan-mobile-2012f.firebaseapp.com',
    storageBucket: 'doan-mobile-2012f.firebasestorage.app',
    measurementId: 'G-J9RQT8H2EC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr9-cF6BHqLjIk-tasIBeGM0PwBHPKaK8',
    appId: '1:834219864810:android:938a454ca768a7376b9d93',
    messagingSenderId: '834219864810',
    projectId: 'doan-mobile-2012f',
    storageBucket: 'doan-mobile-2012f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR_DEdajqb0LldDObwbbggD5KVCkk5dLE',
    appId: '1:834219864810:ios:ca42da058097a75d6b9d93',
    messagingSenderId: '834219864810',
    projectId: 'doan-mobile-2012f',
    storageBucket: 'doan-mobile-2012f.firebasestorage.app',
    iosBundleId: 'com.example.doanMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR_DEdajqb0LldDObwbbggD5KVCkk5dLE',
    appId: '1:834219864810:ios:ca42da058097a75d6b9d93',
    messagingSenderId: '834219864810',
    projectId: 'doan-mobile-2012f',
    storageBucket: 'doan-mobile-2012f.firebasestorage.app',
    iosBundleId: 'com.example.doanMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtdhMWWY5YANFCtffF6UWdhCzJ4xADick',
    appId: '1:834219864810:web:53be8936445460056b9d93',
    messagingSenderId: '834219864810',
    projectId: 'doan-mobile-2012f',
    authDomain: 'doan-mobile-2012f.firebaseapp.com',
    storageBucket: 'doan-mobile-2012f.firebasestorage.app',
    measurementId: 'G-5ZT0Z3SN45',
  );
}
